project_id = "zpolliyfxojotuszomhj"

[functions.analyze-notice]
verify_jwt = true

[functions.send-intro-email]
verify_jwt = true

[functions.send-status-update]
verify_jwt = true

[functions.send-message-notification]
verify_jwt = true
