project_id = "zpolliyfxojotuszomhj"

[functions.analyze-notice]
verify_jwt = true

[functions.send-intro-email]
verify_jwt = true

[functions.send-status-update]
verify_jwt = true

[functions.send-message-notification]
verify_jwt = true

[functions.send-document-request]
verify_jwt = true

[functions.send-document-rejection]
verify_jwt = true

[functions.send-document-upload-notification]
verify_jwt = true

[functions.send-client-reminder]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true
